language: ruby
rvm:
  - 2.2.3
before_install:
  - gem update --system
  - gem --version
install:
  - bundle install --without development --deployment --jobs=3 --retry=3
cache: bundler
provider: script
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake test
